# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#pip install mediapipe
#pip install opencv-python

import cv2
import mediapipe as mp

webcam = cv2.VideoCapture(0)
reconhecimento = mp.solutions.face_detection
reconhecedor_rostos = reconhecimento.FaceDetection()
desenho = mp.solutions.drawing_utils

while True:
  verificador , frame = webcam.read()
  if not verificador:
    break
  lista_rostos = reconhecedor_rostos.process(frame)
  if lista_rostos.detections:
    for rosto in lista_rostos.detections:
      desenho.draw_detection(frame, rosto)
  cv2.imshow("Rostos na webcam", frame)
  if cv2.waitKey(5) == 27: #27 codigo da tecla ESC
    break
webcam.release()
cv2.destroyAllWindows()